apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-db-pv
spec:
  capacity:
    storage: 2Gi  # Set the desired storage size
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ././././Microservices/UserService/data # Replace with the path on the host where data is stored