// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserService.Data;

#nullable disable

namespace UserService.Migrations
{
    [DbContext(typeof(UserDBContext))]
    [Migration("20231218214558_InitalMigration")]
    partial class InitalMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserService.Identity.User", b =>
                {
                    b.Property<string>("AuthzId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Last_seen")
                        .HasColumnType("datetime2");

                    b.HasKey("AuthzId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            AuthzId = "6567896db88a4affe7295ec2",
                            Birthday = new DateOnly(2001, 1, 26),
                            Email = "a.hanga@student.fontys.nl",
                            FirstName = "Andrija",
                            IsActive = true,
                            LastName = "Hanga",
                            Last_seen = new DateTime(2023, 12, 18, 21, 45, 58, 476, DateTimeKind.Utc).AddTicks(6148)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
