version: '3.8'

services:

  db:
    container_name: user_db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "test@123"
      ACCEPT_EULA: Y
    ports:
      - "1401:1433"
    volumes:
      - ./Microservices/UserService/data:/var/opt/mssql/data
      - ./Microservices/UserService/log:/var/mssql/log
      - ./Microservices/UserService/secrets:/var/opt/mssql/secrets
    networks:
      - backend


  user-service:
    container_name: user_service
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: ./Microservices/UserService
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - DbServer=db
      - DbPort=1401
      - DbUser=sa
      - Password=test@123
      - DbName=user_service
    networks:
      - backend

  apigateway:
    container_name: api-gateway
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: ./APIGateway/
      dockerfile: Dockerfile
    ports:
      - "8001:8080"
    networks:
      - backend


networks:
  backend:
    driver: bridge