apiVersion: apps/v1
kind: Deployment
metadata:
    name: userserivce
spec:
    replicas: 1
    selector:
        matchLabels:
            app: userservice
    template:
        metadata:
            labels:
                app: userservice
        spec:
            containers:
                - name: userservice
                  image: andrija121/userservice:latest
                  ports:
                    - containerPort: 8080
                  envFrom:
                    - configMapRef:
                        name: userservice-config