apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigw
  template:
    metadata:
      labels:
        app: apigw
    spec:
      containers:
        - name: apigw
          image: andrija121/apigateway:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: apigw-config