apiVersion: v1
kind: Service
metadata:
  name: apigw
spec:
  selector:
    app: apigw
  ports:
    - protocol: TCP
      port: 8001 # External port
      targetPort: 8080 # Internal container port
  type: LoadBalancer
