// <auto-generated />
using FriendshipService.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FriendshipService.Migrations
{
    [DbContext(typeof(FriendshipDBContext))]
    [Migration("20240111091759_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FriendshipService.Models.Friendship", b =>
                {
                    b.Property<int>("FriendshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FriendshipId"));

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("User_1_AuthzId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_2_AuthzId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FriendshipId");

                    b.ToTable("Friendships");
                });
#pragma warning restore 612, 618
        }
    }
}
