apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5672  # RabbitMQ default port
      targetPort: 5672
  type: ClusterIP