name: Deploy to AKS

on:
  push:
    paths:
      - '**/*'
      - '!/.github/workflows/**'    
    branches: [ "master", "development" ]
    
  pull_request:
      paths:
        - '**/*'
        - '!/.github/workflows/**'
      branches: [ "master", "development" ]  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          context: your-aks-cluster-context

      - name: Deploy to AKS
        run: kubectl apply -f path/to/your/k8s/deployment.yaml

