name: Build and Push Docker Images

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout node
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          registry: https://index.docker.io/v1/

      - name: Build and push Docker images
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t andrija121/friendship-service:latest .
          docker buildx build --platform linux/amd64,linux/arm64 -t andrija121/user-service:latest .
          docker buildx build --platform linux/amd64,linux/arm64 -t andrija121/apigateway:latest /ApiGateway
          docker buildx build --platform linux/amd64,linux/arm64 -t andrija121/rabbitmq:3-management-alpine /RabbitMQ
          docker buildx build --platform linux/amd64,linux/arm64 -t andrija121/react-frontend:latest /fe

          docker push andrija121/user-service:latest
          docker push andrija121/friendship-service:latest
          docker push andrija121/apigateway:latest
          docker push andrija121/rabbitmq:3-management-alpine
          docker push andrija121/react-frontend:latest
